### ISSUE TITLE
UHF Panel: restore viewing of com frequency

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#439] opened 2022-01-17 15:50 UTC
Right now the UHF panel displays NAV freq, since Mumble-FGCom might roll out at some point, it would be nice to have UHF displayed again.

**Comment by NikolaiVChr** [comment] 2022-01-20 00:12
What are we talking about? DED panel?
FG don't really have support for UHF. Its really all VHF.
There is 2 channels com 1 and com 2, and com 1 is also used for nav.

**Comment by NikolaiVChr** [comment] 2022-01-20 07:08
Duplicate of #349

**Closed by NikolaiVChr** 2022-01-20 07:08 UTC
Labels: Enhancement, Low priority
