### ISSUE TITLE
AIM-120 fired at scenario opponent crashes fg

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#517] opened 2023-01-19 14:18 UTC
AIM-120 fired at scenario 0 opponent crashes fg if it hits.

**Comment by BobDotCom** [comment] 2023-04-27 00:42
I cannot reproduce this issue (see here: https://discord.com/channels/379782363061813248/496121096492417025/1098660482384138261). If anyone has detailed reproduction steps that would be really helpful, otherwise this can probably be closed if the bug no longer occurs.

**Comment by sryu1** [comment] 2023-04-27 12:03
I was able to reproduce it a few months ago but after that, didn't really do that scenario, I'll try again when I get some time.

**Comment by BobDotCom** [comment] 2023-05-10 20:41
Might be safe to close this unless someone can reproduce it, I can't seem to find any way to trigger it.

**Closed** 2023-05-10 20:44 UTC
Labels: Medium Priority
