### ISSUE TITLE
Animate gear collapse when parameters are met

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#461] opened 2022-02-19 16:14 UTC
Right now it collapses without visible animation, probably the animation used in the F-15 could help.

**Comment by NikolaiVChr** [comment] 2022-06-24 23:59
Duplicate of #76

**Closed** 2022-06-24 23:59 UTC
Labels: Duplicate, Enhancement

**Comment by JMaverick16** [comment] 2022-06-25 05:27
This was actually meant as visually seeing the gear break apart and collapsing, not just the code.

**Comment by NikolaiVChr** [comment] 2022-06-25 05:34
Its a duplicate thats what the other is about too.
