### ISSUE TITLE
Any way to lock targets or coordinates with the helmet [HMCS]?

### ISSUE THREAD

**Issue by RenanMsV** [NikolaiVChr/f16#527] opened 2023-03-24 00:30 UTC
Something like this shown here in this video:

https://youtube.com/watch?v=JjlwCTDgMBk&si=EnSIkaIECMiOmarE&t=205

**Comment by SammySkycrafts** [comment] 2023-03-24 00:40
Not right now - The only sensor slewing that can be done is slewing AIM-9 Seekers, or slewing the radar and locking up targets when using Dogfight mode with the radar mode set to BORE (Boresight) - See https://github.com/NikolaiVChr/f16/wiki/Radar-ACM-modes) for more info on the ACM radar modes, and for AIM-9 operation, see here: https://github.com/NikolaiVChr/f16/wiki/Radar-ACM-modes

**Comment by BobDotCom** [comment] 2023-05-10 20:47
Duplicate of #491?

**Comment by NikolaiVChr** [comment] 2023-05-12 10:14
Yes, indeed it is, closing as duplicate

**Closed by NikolaiVChr** 2023-05-12 10:14 UTC
Labels: Question
