### ISSUE TITLE
AP: STRG SEL working with stpt #500

### ISSUE THREAD

**Issue by SammySkycrafts** [NikolaiVChr/f16#507] opened 2022-12-19 23:15 UTC
STRG Select doesnt work with STPT#500, Havent tested with any other than route points so not sure if its also the case with those.

**Comment by NikolaiVChr** [comment] 2022-12-20 23:03
Duplicate of #419

**Comment by NikolaiVChr** [comment] 2022-12-20 23:17
Fixed with 31333a17

**Closed by NikolaiVChr** 2022-12-20 23:17 UTC
