### ISSUE TITLE
AP: HSI heading should be followed by HDG SEL

### ISSUE THREAD

**Issue by JMaverick16** [NikolaiVChr/f16#384] opened 2021-12-11 14:14 UTC
https://cdn.discordapp.com/attachments/379793816854724609/918544457652138025/tempFileForShare_20211209-201726.jpg

As noted by Babak:

> we can change this line
> https://github.com/NikolaiVChr/f16/blob/e46d410346c73bd832e2ffaa8a367c7a76eadcba/Systems/autoflight-rules.xml#L86
> to 
> `<property>/instrumentation/heading-indicator-fg/offset-deg</property>`
> 
> However I guess we need some PID tuning as well. It's responding so slowly.

Should be a feature for Blocks 40/50/60, unsure about the older ones, would need a cross-checking.

@Octal450 Any chances you could give it a look?

**Comment by Octal450** [comment] 2021-12-11 14:43
The problem is not PID tuning, the issue is the hdg hold system was not designed to be used like that, I wasn't aware that functionality was supposed to be.

I will look into this asap. Should be a quick fix.

Kind Regards,
Josh

**Comment by BabakAkbari** [comment] 2021-12-11 15:07
Dear @Octal450 
I didn't say the problem is PID tuning. I said we can improve the response by tuning the gains.
As I said we can change [line 86](https://github.com/NikolaiVChr/f16/blob/e46d410346c73bd832e2ffaa8a367c7a76eadcba/Systems/autoflight-rules.xml#L86) to `<property>/instrumentation/heading-indicator-fg/offset-deg</property>` so that the user can input his desired heading as target heading to the controller using the HSI heading knob.

**Comment by Octal450** [comment] 2021-12-11 15:28
Hi @BabakAkbari That is not why, Its because I did not design the system to respond like that. Its designed to keep existing heading only. 
`/instrumentation/heading-indicator-fg/offset-deg` is not the right property. That is for the alignment of the magnetic scale. 

I will fix it. I see multiple problems preventing this from working right in the way it was designed.

**Comment by Octal450** [comment] 2021-12-16 17:32
Issue can be closed, was fixed in the above pull request.

Kind Regards,
Josh

**Closed** 2021-12-16 17:34 UTC
Labels: Enhancement
