### ISSUE TITLE
Pushback during cold and dark

### ISSUE THREAD

**Issue by niallsalmon** [NikolaiVChr/f16#318] opened 2020-11-03 10:47 UTC
When the plane is cold and dark, the rudder won’t work. This means that I can only pushback only forwards and back and so I will need to turn the plane on to turn the plane with pushback. Can we fix it so that rudder can function w/o ignition (ie. cold & dark)?

**Comment by JMaverick16** [comment] 2020-11-03 10:49
I use diff braking but it's quite uncomfortable. I think it could be fixed indeed.

**Comment by NikolaiVChr** [comment] 2021-01-19 11:26
The nosewheel steering cannot steer in cold and dark as it uses Hydr B and DC bus 1 elec.
The problem is that you cannot steer the pushback.

**Closed** 2021-01-19 11:27 UTC
Labels: BUG, Enhancement, Wont-fix
